export const ProductDummyData = [
    { id: 1, heading: "The Shawshank Redemption", year: 1994, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    { id: 2, heading: "The Godfather", year: 1972, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    { id: 3, heading: "The Godfather: Part II", year: 1974, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    { id: 4, heading: "The Dark Knight", year: 2008, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    { id: 5, heading: "12 Angry Men", year: 1957, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    { id: 6, heading: "Schindler's List", year: 1993, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    { id: 7, heading: "Pulp Fiction", year: 1994, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    {
        id: 8, heading: "The Lord of the Rings: The Return of the King",
        year: 2003, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5,
    },
    { id: 9, heading: "The Good, the Bad and the Ugly", year: 1966, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    { id: 10, heading: "Fight Club", year: 1999, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    {
        id: 11, heading: "The Lord of the Rings: The Fellowship of the Ring",
        year: 2001, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5,
    },
    {
        id: 12, heading: "Star Wars: Episode V - The Empire Strikes Back",
        year: 1980, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5,
    },
    { id: 13, heading: "Forrest Gump", year: 1994, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    { id: 14, heading: "Inception", year: 2010, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    {
        id: 15, heading: "The Lord of the Rings: The Two Towers",
        year: 2002, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5,
    },
    { id: 16, heading: "One Flew Over the Cuckoo's Nest", year: 1975, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    { id: 17, heading: "Goodfellas", year: 1990, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    { id: 18, heading: "The Matrix", year: 1999, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    { id: 19, heading: "Seven Samurai", year: 1954, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    {
        id: 20, heading: "Star Wars: Episode IV - A New Hope",
        year: 1977, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5,
    },
    { id: 21, heading: "City of God", year: 2002, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    { id: 22, heading: "Se7en", year: 1995, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    { id: 23, heading: "The Silence of the Lambs", year: 1991, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    { id: 24, heading: "It's a Wonderful Life", year: 1946, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    { id: 25, heading: "Life Is Beautiful", year: 1997, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    { id: 26, heading: "The Usual Suspects", year: 1995, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    { id: 27, heading: "Léon: The Professional", year: 1994, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    { id: 28, heading: "Spirited Away", year: 2001, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    { id: 29, heading: "Saving Private Ryan", year: 1998, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    { id: 30, heading: "Once Upon a Time in the West", year: 1968, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    { id: 31, heading: "American History X", year: 1998, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
    { id: 32, heading: "Interstellar", year: 2014, discription: "Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica", money:10,points:5 },
];